version: "3.4"

x-app:
  &default-app
  image: hseeberger/scala-sbt:8u252_1.3.13_2.12.11
  command: sbt assembly
  working_dir: /app
  volumes:
    - "./:/app"
    - "~/.sbt:/root/.sbt"
    - test-volume:/root/.cache/coursier
    - "~/.aws/:/root/.aws"
  environment:
    - ENV_Tag=dev
    - DB_HOST
    - DB_NAME=test
    - DB_PORT=3300
    - DB_USERNAME=mysql
    - DB_PASSWORD

services:

  test:
    <<: *default-app
    command: sbt clean coverage test coverageReport
    environment:
      - ENV_Tag=test

  build:
    <<: *default-app

  migration:
    <<: *default-app
    command: sbt flywayMigrate

  serverless:
    image: softinstigate/serverless
    command: sls deploy -v
    volumes:
      - "./:/app"
      - "~/.aws/:/root/.aws"

volumes:
  test-volume:
    external: true